const INSIGHT_LABELS = {
  seo_structure: 'SEO Structure',
  messaging_clarity: 'Messaging Clarity',
  cta_usage: 'CTA Usage',
  content_depth: 'Content Depth',
  ux_concerns: 'UX Concerns',
}

export default function InsightsPanel({ insights }) {
  return (
    <div className="panel insights-panel">
      <h2 className="panel-title">AI Insights</h2>
      <p className="panel-subtitle">Generated by Gemini — grounded in the metrics above</p>
      <div className="insights-list">
        {Object.entries(INSIGHT_LABELS).map(([key, label]) => (
          <div key={key} className="insight-item">
            <h3 className="insight-label">{label}</h3>
            <p className="insight-text">{insights[key] || '—'}</p>
          </div>
        ))}
      </div>
    </div>
  )
}
