# Generated by Django 6.0.6 on 2026-06-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('word_count', models.IntegerField(default=0)),
                ('h1_count', models.IntegerField(default=0)),
                ('h2_count', models.IntegerField(default=0)),
                ('h3_count', models.IntegerField(default=0)),
                ('cta_count', models.IntegerField(default=0)),
                ('internal_links', models.IntegerField(default=0)),
                ('external_links', models.IntegerField(default=0)),
                ('image_count', models.IntegerField(default=0)),
                ('images_missing_alt', models.IntegerField(default=0)),
                ('meta_title', models.TextField(blank=True)),
                ('meta_description', models.TextField(blank=True)),
                ('ai_insights', models.JSONField(default=dict)),
                ('recommendations', models.JSONField(default=list)),
                ('prompt_log_file', models.CharField(blank=True, max_length=512)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
